package cc.mikaka.calm.goods.entity;

public class DictDetail extends BaseEntity {
    /**
     * id-主键
     */
    private Long id;

    /**
     * tenant_id-租户ID
     */
    private String tenantId;

    /**
     * remark-备注
     */
    private String remark;

    /**
     * detail_id
     */
    private String detailId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.id
     *
     * @return the value of dict_detail.id
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.id
     *
     * @param id the value for dict_detail.id
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.tenant_id
     *
     * @return the value of dict_detail.tenant_id
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.tenant_id
     *
     * @param tenantId the value for dict_detail.tenant_id
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.remark
     *
     * @return the value of dict_detail.remark
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.remark
     *
     * @param remark the value for dict_detail.remark
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.detail_id
     *
     * @return the value of dict_detail.detail_id
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public String getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.detail_id
     *
     * @param detailId the value for dict_detail.detail_id
     *
     * @mbg.generated Wed Nov 03 13:41:58 CST 2021
     */
    public void setDetailId(String detailId) {
        this.detailId = detailId == null ? null : detailId.trim();
    }
}